<?php list($w, $h) = $this->getEmbedDimensions() ?>
<div class="hs-all-container" style="width: <?php echo $w ?>; height: <?php echo $h ?>;">
	<ul class="hs-spot-container">
		<?php foreach ($this->getSpots() as $spot): ?>
			<?php list($l, $t) = $this->getSpotPosition($spot); ?>
			<li class="hs-spot" style="left: <?php echo $l ?>; top: <?php echo $t ?>;">
				<span class="pin"></span>
				<div class="hs-content">
					<?php echo $this->getContent($spot); ?>
				</div>
			</li>
		<?php endforeach; ?>
	</ul>
	<div class="hs-image">
		<?php $image = $this->resizeImage(); ?>
		<img src="<?php echo $image ?>"/>
	</div>
</div>
